---
<<<<<<< HEAD
# Hii hello 
=======
yuvi
>>>>>>> 987c386 (Raj)
- name: Demonstrate lineinfile - example2
  hosts: localhost
  become: true
  tasks:
    - name: remove the line
      lineinfile:
        path: /home/ansible/statements.txt
        line:  ^yuvaraj # search for the line that starts with yuvaraj
        state: absent   # remove the line that was found from the above regular expression
...
